test iso in self hosted runner

diff --git a/.github/workflows/iso.yml b/.github/workflows/iso.yml
--- a/.github/workflows/iso.yml
+++ b/.github/workflows/iso.yml
@@ -6,15 +6,13 @@ on:
 env:
   GOPROXY: https://proxy.golang.org
 jobs:
-  # Runs before all other jobs
-  # builds the minikube binaries
-  build_minikube:
-    runs-on: ubuntu-18.04
+  build_test_iso:
+    runs-on: [self-hosted, Ubuntu, 16CPUs, kmv]
     steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-go@v2
         with:
-          go-version: '1.13.9'
+          go-version: '1.14.6'
           stable: true
       - name: Download Dependencies
         run: go mod download
@@ -31,22 +29,6 @@ jobs:
           echo workspace $GITHUB_WORKSPACE
           echo "end of debug stuff"
           echo $(which jq)
-      - uses: actions/upload-artifact@v1
-        with:
-          name: minikube_binaries
-          path: out
-  build_iso:
-    runs-on: ubuntu-18.04
-    env:
-      LANG: en_US.utf8
-    steps:
-      - uses: actions/checkout@v2
-      - uses: actions/setup-go@v2
-        with:
-          go-version: '1.11.13'
-          stable: true
-      - name: Download Dependencies
-        run: go mod download
       - name: Install ISO tools
         run: |
           sudo apt-get update \
@@ -74,62 +56,34 @@ jobs:
         run: |
           IN_DOCKER=1 make out/minikube.iso
           make checksum
-      - uses: actions/upload-artifact@v1
-        with:
-          name: minikube_binaries
-          path: out
-  functional_virtualbox_macos:
-    needs: [build_minikube]
-    env:
-      TIME_ELAPSED: time
-      JOB_NAME: "functional_virtualbox_macos"
-      GOPOGH_RESULT: ""
-      SHELL: "/bin/bash" # To prevent https://github.com/kubernetes/minikube/issues/6643
-    runs-on: macos-10.15
-    steps:
       - name: Install kubectl
         shell: bash
         run: |
-          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/darwin/amd64/kubectl
+          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
           sudo install kubectl /usr/local/bin/kubectl
           kubectl version --client=true
       - name: Install gopogh
         shell: bash
         run: |
-          curl -LO https://github.com/medyagh/gopogh/releases/download/v0.1.23/gopogh-darwin-amd64
+          curl -LO https://github.com/medyagh/gopogh/releases/download/v0.1.23/gopogh-linux-amd64
           sudo install gopogh-darwin-amd64 /usr/local/bin/gopogh
       - name: Install docker
         shell: bash
         run: |
           brew install docker-machine docker
           sudo docker --version
-      - name: Info
-        shell: bash
-        run: |
-          hostname
-          VBoxManage --version
-          sysctl hw.physicalcpu hw.logicalcpu 
-      - name: Disable firewall
-        run: |
-          sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
-          sudo /usr/libexec/ApplicationFirewall/socketfilterfw -k
-      - name: Download Binaries
-        uses: actions/download-artifact@v1
-        with:
-          name: minikube_binaries
       - name: Run Integration Test
         continue-on-error: false
         # bash {0} to allow test to continue to next step. in case of
         shell: bash {0}
         run: |
-          cd minikube_binaries
-          pwd
+          cd out
           mkdir -p report
           mkdir -p testhome
           chmod a+x e2e-*
           chmod a+x minikube-*
           START_TIME=$(date -u +%s)
-          KUBECONFIG=$(pwd)/testhome/kubeconfig MINIKUBE_HOME=$(pwd)/testhome ./e2e-darwin-amd64 -minikube-start-args="--vm-driver=virtualbox --iso-url=file://$(pwd)/out/minikube.iso" -test.run TestFunctional -test.timeout=15m -test.v -timeout-multiplier=1.5 -binary=./minikube-darwin-amd64 2>&1 | tee ./report/testout.txt
+          KUBECONFIG=$(pwd)/testhome/kubeconfig MINIKUBE_HOME=$(pwd)/testhome ./e2e-darwin-amd64 -minikube-start-args="--vm-driver=kvm2 --iso-url=file://$(pwd)/minikube.iso" -test.run TestFunctional -test.timeout=15m -test.v -timeout-multiplier=1.5 -binary=./minikube-darwin-amd64 2>&1 | tee ./report/testout.txt
           END_TIME=$(date -u +%s)
           TIME_ELAPSED=$(($END_TIME-$START_TIME))
           min=$((${TIME_ELAPSED}/60))
@@ -139,7 +93,7 @@ jobs:
       - name: Generate HTML Report
         shell: bash
         run: |
-          cd minikube_binaries
+          cd out
           export PATH=${PATH}:`go env GOPATH`/bin
           go tool test2json -t < ./report/testout.txt > ./report/testout.json || true
           STAT=$(gopogh -in ./report/testout.json -out ./report/testout.html -name "${JOB_NAME} ${GITHUB_REF}" -repo "${GITHUB_REPOSITORY}"  -details "${GITHUB_SHA}")  || true
@@ -151,42 +105,21 @@ jobs:
           echo ::set-env name=STAT::${STAT}
       - uses: actions/upload-artifact@v1
         with:
-          name: functional_virtualbox_macos
-          path: minikube_binaries/report
-      - name: The End Result functional_virtualbox_macos
+          name: iso_functional_test
+          path: out/report
+      - name: The End Result build_test_iso
         shell: bash
         run: |
           echo ${GOPOGH_RESULT}
           numFail=$(echo $STAT | jq '.NumberOfFail')
-          echo "----------------${numFail} Failures----------------------------"
-          echo $STAT | jq '.FailedTests' || true
-          echo "-------------------------------------------------------"
           numPass=$(echo $STAT | jq '.NumberOfPass')
-          echo "*** $numPass Passed ***"
+          echo "*******************${numPass} Passes :) *******************"
+          echo $STAT | jq '.PassedTests' || true
+          echo "*******************************************************"
+          echo "---------------- ${numFail} Failures :( ----------------------------"
+          echo $STAT | jq '.FailedTests' || true
+          echo "-------------------------------------------------------"          numPass=$(echo $STAT | jq '.NumberOfPass')
           if [ "$numFail" -gt 0 ];then echo "*** $numFail Failed ***";exit 2;fi
           if [ "$numPass" -eq 0 ];then echo "*** 0 Passed! ***";exit 2;fi
           if [ "$numPass" -lt 33 ];then echo "*** Failed to pass at least 33 ! ***";exit 2;fi
           if [ "$numPass" -eq 0 ];then echo "*** Passed! ***";exit 0;fi
-  # After all integration tests finished
-  # collect all the reports and upload them
-  upload_all_reports:
-    if: always()
-    needs:
-      [
-        functional_virtualbox_macos,
-      ]
-    runs-on: ubuntu-18.04
-    steps:
-      - name: download all reports
-        uses: actions/download-artifact@v2-preview
-      - name: upload all reports
-        shell: bash {0}
-        continue-on-error: true
-        run: |
-          mkdir -p all_reports
-          ls -lah
-          cp -r ./functional_virtualbox_macos ./all_reports/
-      - uses: actions/upload-artifact@v1
-        with:
-          name: all_reports
-          path: all_reports
