github actions

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -118,15 +118,15 @@ jobs:
       with:
         name: docker_ubuntu_16_04
         path: minikube_binaries/report
-    - name: The End Result
+    - name: The End Result Docker on ubuntu 16:04
       shell: bash
       run: |
         echo ${GOPOGH_RESULT}
-        echo "--------------------------------------------"
+        numFail=$(echo $STAT | jq '.NumberOfFail')
+        echo "----------------${numFail} Failures----------------------------"
         echo $STAT | jq '.FailedTests' || true
-        echo "--------------------------------------------"
-        numberOfFailures=$(echo $STAT | jq '.NumberOfFail')
-        if [ "$numberOfFailures" -gt 0 ];then echo "*** $numberOfFailures Failed ***";exit 2;fi
+        echo "-------------------------------------------------------"
+        if [ "$numFail" -gt 0 ];then echo "*** $numFail Failed ***";exit 2;fi
   docker_ubuntu_18_04:
     runs-on: ubuntu-18.04
     env:
@@ -180,15 +180,15 @@ jobs:
       with:
         name: docker_ubuntu_18_04
         path: minikube_binaries/report
-    - name: The End Result
+    - name: The End Result - Docker On Ubuntu 18:04
       shell: bash
       run: |
         echo ${GOPOGH_RESULT}
-        echo "--------------------------------------------"
+        numFail=$(echo $STAT | jq '.NumberOfFail')
+        echo "----------------${numFail} Failures----------------------------"
         echo $STAT | jq '.FailedTests' || true
-        echo "--------------------------------------------"
-        numberOfFailures=$(echo $STAT | jq '.NumberOfFail')
-        if [ "$numberOfFailures" -gt 0 ];then echo "*** $numberOfFailures Failed ***";exit 2;fi
+        echo "-------------------------------------------------------"
+        if [ "$numFail" -gt 0 ];then echo "*** $numFail Failed ***";exit 2;fi
   none_ubuntu16_04:
     needs: [build_minikube]
     env:
@@ -242,15 +242,15 @@ jobs:
       with:
         name: none_ubuntu16_04
         path: minikube_binaries/report
-    - name: The End Result
+    - name: The End Result - None On Ubuntu 16:04
       shell: bash
       run: |
         echo ${GOPOGH_RESULT}
-        echo "--------------------------------------------"
+        numFail=$(echo $STAT | jq '.NumberOfFail')
+        echo "----------------${numFail} Failures----------------------------"
         echo $STAT | jq '.FailedTests' || true
-        echo "--------------------------------------------"
-        numberOfFailures=$(echo $STAT | jq '.NumberOfFail')
-        if [ "$numberOfFailures" -gt 0 ];then echo "*** $numberOfFailures Failed ***";exit 2;fi
+        echo "-------------------------------------------------------"
+        if [ "$numFail" -gt 0 ];then echo "*** $numFail Failed ***";exit 2;fi
   none_ubuntu18_04:
     needs: [build_minikube]
     env:
@@ -304,15 +304,15 @@ jobs:
       with:
         name: none_ubuntu18_04
         path: minikube_binaries/report
-    - name: The End Result
+    - name: The End Result - None on Ubuntu 18:04
       shell: bash
       run: |
         echo ${GOPOGH_RESULT}
-        echo "--------------------------------------------"
+        numFail=$(echo $STAT | jq '.NumberOfFail')
+        echo "----------------${numFail} Failures----------------------------"
         echo $STAT | jq '.FailedTests' || true
-        echo "--------------------------------------------"
-        numberOfFailures=$(echo $STAT | jq '.NumberOfFail')
-        if [ "$numberOfFailures" -gt 0 ];then echo "*** $numberOfFailures Failed ***";exit 2;fi
+        echo "-------------------------------------------------------"
+        if [ "$numFail" -gt 0 ];then echo "*** $numFail Failed ***";exit 2;fi
   podman_ubuntu_18_04:
       needs: [build_minikube]
       env:
@@ -377,7 +377,7 @@ jobs:
         with:
           name: podman_ubuntu_18_04
           path: minikube_binaries/report
-      - name: The End Result
+      - name: The End Result - Podman On Ubuntu 18:04
         shell: bash
         run: |
           echo ${GOPOGH_RESULT}
@@ -397,8 +397,9 @@ jobs:
       uses: actions/download-artifact@v1
       with:
         name: docker_ubuntu_16_04
-    - name: cp to all_report
-      shell: bash
+    - name: cp docker_ubuntu_16_04 to all_report
+      continue-on-error: true
+      shell: bash {0}
       run: |
         mkdir -p all_reports
         cp -r docker_ubuntu_16_04 ./all_reports/
@@ -406,8 +407,9 @@ jobs:
       uses: actions/download-artifact@v1
       with:
         name: docker_ubuntu_18_04
-    - name: cp to all_report
-      shell: bash
+    - name: cp docker_ubuntu_18_04 to all_report
+      continue-on-error: true
+      shell: bash {0}
       run: |
         mkdir -p all_reports
         cp -r docker_ubuntu_18_04 ./all_reports/
@@ -415,8 +417,9 @@ jobs:
       uses: actions/download-artifact@v1
       with:
         name: none_ubuntu16_04
-    - name: cp to all_report
-      shell: bash
+    - name: cp none_ubuntu16_04 to all_report
+      continue-on-error: true
+      shell: bash {0}
       run: |
         mkdir -p all_reports
         cp -r none_ubuntu16_04 ./all_reports/
@@ -424,8 +427,9 @@ jobs:
       uses: actions/download-artifact@v1
       with:
         name: none_ubuntu18_04
-    - name: cp to all_report
-      shell: bash
+    - name: cp none_ubuntu18_04 to all_report
+      continue-on-error: true
+      shell: bash {0}
       run: |
         mkdir -p all_reports
         cp -r none_ubuntu18_04 ./all_reports/
@@ -433,8 +437,9 @@ jobs:
       uses: actions/download-artifact@v1
       with:
         name: podman_ubuntu_18_04
-    - name: cp to all_report
-      shell: bash
+    - name: cp podman_ubuntu_18_04 to all_report
+      continue-on-error: true
+      shell: bash {0}
       run: |
         mkdir -p all_reports
         cp -r podman_ubuntu_18_04 ./all_reports/
