add gopogh with duration with latest golang

diff --git a/.github/workflows/master.yml b/.github/workflows/master.yml
--- a/.github/workflows/master.yml
+++ b/.github/workflows/master.yml
@@ -101,7 +101,7 @@ jobs:
           echo "--------------------------"
           docker version || true
           echo "--------------------------"
-          docker info --format='{{json .}}' || true
+          docker info  || true
           echo "--------------------------"
           docker system df || true
           echo "--------------------------"
@@ -109,7 +109,13 @@ jobs:
           echo "--------------------------"
           docker ps || true
           echo "--------------------------"
+      # go 1.14.6+ is needed because of this bug https://github.com/golang/go/issues/39308
+      - uses: actions/setup-go@v2
+        with:
+          go-version: '1.14.6'
+          stable: true
       - name: Install gopogh
+
         shell: bash
         run: |
           curl -LO https://github.com/medyagh/gopogh/releases/download/v0.2.3/gopogh-linux-amd64
@@ -160,13 +166,13 @@ jobs:
         run: |
           echo ${GOPOGH_RESULT}
           numFail=$(echo $STAT | jq '.NumberOfFail')
-          echo "----------------${numFail} Failures----------------------------"
-          echo $STAT | jq '.FailedTests' || true
-          echo "-------------------------------------------------------"
           numPass=$(echo $STAT | jq '.NumberOfPass')
           echo "*******************${numPass} Passes :) *******************"
           echo $STAT | jq '.PassedTests' || true
           echo "*******************************************************"
+          echo "---------------- ${numFail} Failures :( ----------------------------"
+          echo $STAT | jq '.FailedTests' || true
+          echo "-------------------------------------------------------"
           if [ "$numFail" -gt 0 ];then echo "*** $numFail Failed ***";exit 2;fi
           if [ "$numPass" -eq 0 ];then echo "*** 0 Passed! ***";exit 2;fi
           if [ "$numPass" -lt 36 ];then echo "*** Failed to pass at least 36 ! ***";exit 2;fi
@@ -186,7 +192,13 @@ jobs:
           curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/darwin/amd64/kubectl
           sudo install kubectl /usr/local/bin/kubectl
           kubectl version --client=true
+      # go 1.14.6+ is needed because of this bug https://github.com/golang/go/issues/39308
+      - uses: actions/setup-go@v2
+        with:
+          go-version: '1.14.6'
+          stable: true
       - name: Install gopogh
+
         shell: bash
         run: |
           curl -LO https://github.com/medyagh/gopogh/releases/download/v0.2.3/gopogh-darwin-amd64
@@ -250,13 +262,13 @@ jobs:
         run: |
           echo ${GOPOGH_RESULT}
           numFail=$(echo $STAT | jq '.NumberOfFail')
-          echo "----------------${numFail} Failures :(----------------------------"
-          echo $STAT | jq '.FailedTests' || true
-          echo "-------------------------------------------------------"
           numPass=$(echo $STAT | jq '.NumberOfPass')
           echo "*******************${numPass} Passes :) *******************"
           echo $STAT | jq '.PassedTests' || true
           echo "*******************************************************"
+          echo "----------------${numFail} Failures :(----------------------------"
+          echo $STAT | jq '.FailedTests' || true
+          echo "-------------------------------------------------------"
           if [ "$numFail" -gt 0 ];then echo "*** $numFail Failed ***";exit 2;fi
           if [ "$numPass" -eq 0 ];then echo "*** 0 Passed! ***";exit 2;fi
           if [ "$numPass" -lt 33 ];then echo "*** Failed to pass at least 33 ! ***";exit 2;fi
@@ -304,6 +316,10 @@ jobs:
           echo "------------------------"
           docker volume ls
           echo "------------------------"
+      - uses: actions/setup-go@v2
+        with:
+          go-version: '1.14.6'
+          stable: true
       - name: Install tools
         continue-on-error: true
         shell: powershell
@@ -351,7 +367,7 @@ jobs:
           echo ${GOPOGH_RESULT}
           $numFail=(echo $STAT | jq '.NumberOfFail')
           $failedTests=( echo $STAT | jq '.FailedTests')
-          echo "----------------${numFail} Failures----------------------------"
+          echo "---------------- ${numFail} Failures :( ----------------------------"
           echo $failedTest
           echo "-------------------------------------------------------"
           $numPass=$(echo $STAT | jq '.NumberOfPass')
@@ -365,14 +381,14 @@ jobs:
         run: |
           $numFail=(echo $Env:STAT | jq '.NumberOfFail')
           $failedTests=( echo $Env:STAT | jq '.FailedTests')
-          echo "----------------${numFail} Failures----------------------------"
-          echo $failedTests
-          echo "-------------------------------------------------------"
           $numPass=$(echo $Env:STAT | jq '.NumberOfPass')
-          $passedTests=( echo $Env:STAT | jq '.PassedTests'
+          $passedTests=( echo $Env:STAT | jq '.PassedTests')
           echo "*******************${numPass} Passes :) *******************"
           echo $passedTests
           echo "*******************************************************"
+          echo "---------------- ${numFail} Failures :( ----------------------------"
+          echo $failedTests
+          echo "-------------------------------------------------------"
           If ($numFail -gt 0){ exit 2 } 
           If ($numPass -eq 0){ exit 2 }
           If ($numPass -lt 33){ exit 2 }
@@ -417,6 +433,10 @@ jobs:
           ls 
           echo $env:computername
           Get-WmiObject -class Win32_ComputerSystem
+      - uses: actions/setup-go@v2
+        with:
+          go-version: '1.14.6'
+          stable: true
       - name: Install tools
         continue-on-error: true
         shell: powershell
@@ -465,7 +485,7 @@ jobs:
           echo ${GOPOGH_RESULT}
           $numFail=(echo $STAT | jq '.NumberOfFail')
           $failedTests=( echo $STAT | jq '.FailedTests')
-          echo "----------------${numFail} Failures----------------------------"
+          echo "---------------- ${numFail} Failures :( ----------------------------"
           echo $failedTest
           echo "-------------------------------------------------------"
           $numPass=$(echo $STAT | jq '.NumberOfPass')
@@ -479,14 +499,14 @@ jobs:
         run: |
           $numFail=(echo $Env:STAT | jq '.NumberOfFail')
           $failedTests=( echo $Env:STAT | jq '.FailedTests')
-          echo "----------------${numFail} Failures----------------------------"
-          echo $failedTests
-          echo "-------------------------------------------------------"
           $numPass=$(echo $Env:STAT | jq '.NumberOfPass')
-          $passedTests=( echo $Env:STAT | jq '.PassedTests'
+          $passedTests=( echo $Env:STAT | jq '.PassedTests')
           echo "*******************${numPass} Passes :) *******************"
           echo $passedTests
           echo "*******************************************************"
+          echo "---------------- ${numFail} Failures :( ----------------------------"
+          echo $failedTests
+          echo "-------------------------------------------------------"
           If ($numFail -gt 0){ exit 2 } 
           If ($numPass -eq 0){ exit 2 }
           If ($numPass -lt 33){ exit 2 }
@@ -517,7 +537,13 @@ jobs:
           VERSION="v1.17.0"
           curl -L https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/crictl-${VERSION}-linux-amd64.tar.gz --output crictl-${VERSION}-linux-amd64.tar.gz
           sudo tar zxvf crictl-$VERSION-linux-amd64.tar.gz -C /usr/local/bin
+      # go 1.14.6+ is needed because of this bug https://github.com/golang/go/issues/39308
+      - uses: actions/setup-go@v2
+        with:
+          go-version: '1.14.6'
+          stable: true
       - name: Install gopogh
+
         shell: bash
         run: |
           curl -LO https://github.com/medyagh/gopogh/releases/download/v0.2.3/gopogh-linux-amd64
@@ -566,13 +592,13 @@ jobs:
         run: |
           echo ${GOPOGH_RESULT}
           numFail=$(echo $STAT | jq '.NumberOfFail')
-          echo "----------------${numFail} Failures----------------------------"
-          echo $STAT | jq '.FailedTests' || true
-          echo "-------------------------------------------------------"
           numPass=$(echo $STAT | jq '.NumberOfPass')
           echo "*******************${numPass} Passes :) *******************"
           echo $STAT | jq '.PassedTests' || true
           echo "*******************************************************"
+          echo "---------------- ${numFail} Failures :( ----------------------------"
+          echo $STAT | jq '.FailedTests' || true
+          echo "-------------------------------------------------------"
           if [ "$numFail" -gt 0 ];then echo "*** $numFail Failed ***";exit 2;fi
           if [ "$numPass" -eq 0 ];then echo "*** 0 Passed! ***";exit 2;fi
           if [ "$numPass" -lt 26 ];then echo "*** Failed to pass at least 26 ! ***";exit 2;fi
@@ -606,7 +632,13 @@ jobs:
           echo "--------------------------"
           docker ps || true
           echo "--------------------------"
+      # go 1.14.6+ is needed because of this bug https://github.com/golang/go/issues/39308
+      - uses: actions/setup-go@v2
+        with:
+          go-version: '1.14.6'
+          stable: true
       - name: Install gopogh
+
         shell: bash
         run: |
           curl -LO https://github.com/medyagh/gopogh/releases/download/v0.2.3/gopogh-linux-amd64
@@ -655,13 +687,13 @@ jobs:
         run: |
           echo ${GOPOGH_RESULT}
           numFail=$(echo $STAT | jq '.NumberOfFail')
-          echo "----------------${numFail} Failures----------------------------"
-          echo $STAT | jq '.FailedTests' || true
-          echo "-------------------------------------------------------"
           numPass=$(echo $STAT | jq '.NumberOfPass')
           echo "*******************${numPass} Passes :) *******************"
           echo $STAT | jq '.PassedTests' || true
           echo "*******************************************************"
+          echo "---------------- ${numFail} Failures :( ----------------------------"
+          echo $STAT | jq '.FailedTests' || true
+          echo "-------------------------------------------------------"
           if [ "$numFail" -gt 0 ];then echo "*** $numFail Failed ***";exit 2;fi
           if [ "$numPass" -eq 0 ];then echo "*** 0 Passed! ***";exit 2;fi
           if [ "$numPass" -lt 5 ];then echo "*** Failed to pass at least 5 ! ***";exit 2;fi
@@ -680,7 +712,13 @@ jobs:
           curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/darwin/amd64/kubectl
           sudo install kubectl /usr/local/bin/kubectl
           kubectl version --client=true
+      # go 1.14.6+ is needed because of this bug https://github.com/golang/go/issues/39308
+      - uses: actions/setup-go@v2
+        with:
+          go-version: '1.14.6'
+          stable: true
       - name: Install gopogh
+
         shell: bash
         run: |
           curl -LO https://github.com/medyagh/gopogh/releases/download/v0.2.3/gopogh-darwin-amd64
@@ -744,13 +782,13 @@ jobs:
         run: |
           echo ${GOPOGH_RESULT}
           numFail=$(echo $STAT | jq '.NumberOfFail')
-          echo "----------------${numFail} Failures----------------------------"
-          echo $STAT | jq '.FailedTests' || true
-          echo "-------------------------------------------------------"
           numPass=$(echo $STAT | jq '.NumberOfPass')
           echo "*******************${numPass} Passes :) *******************"
           echo $STAT | jq '.PassedTests' || true
           echo "*******************************************************"
+          echo "---------------- ${numFail} Failures :( ----------------------------"
+          echo $STAT | jq '.FailedTests' || true
+          echo "-------------------------------------------------------"
           if [ "$numFail" -gt 0 ];then echo "*** $numFail Failed ***";exit 2;fi
           if [ "$numPass" -eq 0 ];then echo "*** 0 Passed! ***";exit 2;fi
           if [ "$numPass" -lt 5 ];then echo "*** Failed to pass at least 5 ! ***";exit 2;fi
@@ -783,7 +821,13 @@ jobs:
           echo "--------------------------"
           docker ps || true
           echo "--------------------------"
+      # go 1.14.6+ is needed because of this bug https://github.com/golang/go/issues/39308
+      - uses: actions/setup-go@v2
+        with:
+          go-version: '1.14.6'
+          stable: true
       - name: Install gopogh
+
         shell: bash
         run: |
           curl -LO https://github.com/medyagh/gopogh/releases/download/v0.2.3/gopogh-linux-amd64
@@ -834,13 +878,13 @@ jobs:
         run: |
           echo ${GOPOGH_RESULT}
           numFail=$(echo $STAT | jq '.NumberOfFail')
-          echo "----------------${numFail} Failures----------------------------"
-          echo $STAT | jq '.FailedTests' || true
-          echo "-------------------------------------------------------"
           numPass=$(echo $STAT | jq '.NumberOfPass')
           echo "*******************${numPass} Passes :) *******************"
           echo $STAT | jq '.PassedTests' || true
           echo "*******************************************************"
+          echo "---------------- ${numFail} Failures :( ----------------------------"
+          echo $STAT | jq '.FailedTests' || true
+          echo "-------------------------------------------------------"
           if [ "$numFail" -gt 0 ];then echo "*** $numFail Failed ***";exit 2;fi
           if [ "$numPass" -eq 0 ];then echo "*** 0 Passed! ***";exit 2;fi
           if [ "$numPass" -lt 5 ];then echo "*** Failed to pass at least 5 ! ***";exit 2;fi
@@ -859,7 +903,13 @@ jobs:
           curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/darwin/amd64/kubectl
           sudo install kubectl /usr/local/bin/kubectl
           kubectl version --client=true
+      # go 1.14.6+ is needed because of this bug https://github.com/golang/go/issues/39308
+      - uses: actions/setup-go@v2
+        with:
+          go-version: '1.14.6'
+          stable: true
       - name: Install gopogh
+
         shell: bash
         run: |
           curl -LO https://github.com/medyagh/gopogh/releases/download/v0.2.3/gopogh-darwin-amd64
@@ -918,13 +968,13 @@ jobs:
         run: |
           echo ${GOPOGH_RESULT}
           numFail=$(echo $STAT | jq '.NumberOfFail')
-          echo "----------------${numFail} Failures----------------------------"
-          echo $STAT | jq '.FailedTests' || true
-          echo "-------------------------------------------------------"
           numPass=$(echo $STAT | jq '.NumberOfPass')
           echo "*******************${numPass} Passes :) *******************"
           echo $STAT | jq '.PassedTests' || true
           echo "*******************************************************"
+          echo "---------------- ${numFail} Failures :( ----------------------------"
+          echo $STAT | jq '.FailedTests' || true
+          echo "-------------------------------------------------------"
           if [ "$numFail" -gt 0 ];then echo "*** $numFail Failed ***";exit 2;fi
           if [ "$numPass" -eq 0 ];then echo "*** 0 Passed! ***";exit 2;fi
           if [ "$numPass" -lt 7 ];then echo "*** Failed to pass at least 7 ! ***";exit 2;fi
@@ -957,7 +1007,13 @@ jobs:
           echo "--------------------------"
           docker ps || true
           echo "--------------------------"
+      # go 1.14.6+ is needed because of this bug https://github.com/golang/go/issues/39308
+      - uses: actions/setup-go@v2
+        with:
+          go-version: '1.14.6'
+          stable: true
       - name: Install gopogh
+
         shell: bash
         run: |
           curl -LO https://github.com/medyagh/gopogh/releases/download/v0.2.3/gopogh-linux-amd64
@@ -1006,13 +1062,14 @@ jobs:
         run: |
           echo ${GOPOGH_RESULT}
           numFail=$(echo $STAT | jq '.NumberOfFail')
-          echo "----------------${numFail} Failures----------------------------"
-          echo $STAT | jq '.FailedTests' || true
-          echo "-------------------------------------------------------"
           numPass=$(echo $STAT | jq '.NumberOfPass')
           echo "*******************${numPass} Passes :) *******************"
           echo $STAT | jq '.PassedTests' || true
-          echo "*******************************************************"          if [ "$numFail" -gt 0 ];then echo "*** $numFail Failed ***";exit 2;fi
+          echo "*******************************************************"
+          echo "---------------- ${numFail} Failures :( ----------------------------"
+          echo $STAT | jq '.FailedTests' || true
+          echo "-------------------------------------------------------"
+          if [ "$numFail" -gt 0 ];then echo "*** $numFail Failed ***";exit 2;fi
           if [ "$numPass" -eq 0 ];then echo "*** 0 Passed! ***";exit 2;fi
           if [ "$numPass" -lt 9 ];then echo "*** Failed to pass at least 9 ! ***";exit 2;fi
   pause_preload_dockerflags_virtualbox_macos:
@@ -1030,7 +1087,13 @@ jobs:
           curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/darwin/amd64/kubectl
           sudo install kubectl /usr/local/bin/kubectl
           kubectl version --client=true
+      # go 1.14.6+ is needed because of this bug https://github.com/golang/go/issues/39308
+      - uses: actions/setup-go@v2
+        with:
+          go-version: '1.14.6'
+          stable: true
       - name: Install gopogh
+
         shell: bash
         run: |
           curl -LO https://github.com/medyagh/gopogh/releases/download/v0.2.3/gopogh-darwin-amd64
@@ -1089,13 +1152,13 @@ jobs:
         run: |
           echo ${GOPOGH_RESULT}
           numFail=$(echo $STAT | jq '.NumberOfFail')
-          echo "----------------${numFail} Failures----------------------------"
-          echo $STAT | jq '.FailedTests' || true
-          echo "-------------------------------------------------------"
           numPass=$(echo $STAT | jq '.NumberOfPass')
           echo "*******************${numPass} Passes :) *******************"
           echo $STAT | jq '.PassedTests' || true
           echo "*******************************************************"
+          echo "---------------- ${numFail} Failures :( ----------------------------"
+          echo $STAT | jq '.FailedTests' || true
+          echo "-------------------------------------------------------"
           if [ "$numFail" -gt 0 ];then echo "*** $numFail Failed ***";exit 2;fi
           if [ "$numPass" -eq 0 ];then echo "*** 0 Passed! ***";exit 2;fi
           if [ "$numPass" -lt 9 ];then echo "*** Failed to pass at least 9 ! ***";exit 2;fi
diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -99,7 +99,7 @@ jobs:
           echo "--------------------------"
           docker version || true
           echo "--------------------------"
-          docker info --format='{{json .}}' || true
+          docker info  || true
           echo "--------------------------"
           docker system df || true
           echo "--------------------------"
@@ -107,7 +107,13 @@ jobs:
           echo "--------------------------"
           docker ps || true
           echo "--------------------------"
+      # go 1.14.6+ is needed because of this bug https://github.com/golang/go/issues/39308
+      - uses: actions/setup-go@v2
+        with:
+          go-version: '1.14.6'
+          stable: true
       - name: Install gopogh
+
         shell: bash
         run: |
           curl -LO https://github.com/medyagh/gopogh/releases/download/v0.2.3/gopogh-linux-amd64
@@ -158,13 +164,13 @@ jobs:
         run: |
           echo ${GOPOGH_RESULT}
           numFail=$(echo $STAT | jq '.NumberOfFail')
-          echo "----------------${numFail} Failures----------------------------"
-          echo $STAT | jq '.FailedTests' || true
-          echo "-------------------------------------------------------"
           numPass=$(echo $STAT | jq '.NumberOfPass')
           echo "*******************${numPass} Passes :) *******************"
           echo $STAT | jq '.PassedTests' || true
           echo "*******************************************************"
+          echo "---------------- ${numFail} Failures :( ----------------------------"
+          echo $STAT | jq '.FailedTests' || true
+          echo "-------------------------------------------------------"
           if [ "$numFail" -gt 0 ];then echo "*** $numFail Failed ***";exit 2;fi
           if [ "$numPass" -eq 0 ];then echo "*** 0 Passed! ***";exit 2;fi
           if [ "$numPass" -lt 36 ];then echo "*** Failed to pass at least 36 ! ***";exit 2;fi
@@ -184,7 +190,13 @@ jobs:
           curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/darwin/amd64/kubectl
           sudo install kubectl /usr/local/bin/kubectl
           kubectl version --client=true
+      # go 1.14.6+ is needed because of this bug https://github.com/golang/go/issues/39308
+      - uses: actions/setup-go@v2
+        with:
+          go-version: '1.14.6'
+          stable: true
       - name: Install gopogh
+
         shell: bash
         run: |
           curl -LO https://github.com/medyagh/gopogh/releases/download/v0.2.3/gopogh-darwin-amd64
@@ -248,13 +260,13 @@ jobs:
         run: |
           echo ${GOPOGH_RESULT}
           numFail=$(echo $STAT | jq '.NumberOfFail')
-          echo "----------------${numFail} Failures :(----------------------------"
-          echo $STAT | jq '.FailedTests' || true
-          echo "-------------------------------------------------------"
           numPass=$(echo $STAT | jq '.NumberOfPass')
           echo "*******************${numPass} Passes :) *******************"
           echo $STAT | jq '.PassedTests' || true
           echo "*******************************************************"
+          echo "----------------${numFail} Failures :(----------------------------"
+          echo $STAT | jq '.FailedTests' || true
+          echo "-------------------------------------------------------"
           if [ "$numFail" -gt 0 ];then echo "*** $numFail Failed ***";exit 2;fi
           if [ "$numPass" -eq 0 ];then echo "*** 0 Passed! ***";exit 2;fi
           if [ "$numPass" -lt 33 ];then echo "*** Failed to pass at least 33 ! ***";exit 2;fi
@@ -302,6 +314,10 @@ jobs:
           echo "------------------------"
           docker volume ls
           echo "------------------------"
+      - uses: actions/setup-go@v2
+        with:
+          go-version: '1.14.6'
+          stable: true
       - name: Install tools
         continue-on-error: true
         shell: powershell
@@ -349,7 +365,7 @@ jobs:
           echo ${GOPOGH_RESULT}
           $numFail=(echo $STAT | jq '.NumberOfFail')
           $failedTests=( echo $STAT | jq '.FailedTests')
-          echo "----------------${numFail} Failures----------------------------"
+          echo "---------------- ${numFail} Failures :( ----------------------------"
           echo $failedTest
           echo "-------------------------------------------------------"
           $numPass=$(echo $STAT | jq '.NumberOfPass')
@@ -363,14 +379,14 @@ jobs:
         run: |
           $numFail=(echo $Env:STAT | jq '.NumberOfFail')
           $failedTests=( echo $Env:STAT | jq '.FailedTests')
-          echo "----------------${numFail} Failures----------------------------"
-          echo $failedTests
-          echo "-------------------------------------------------------"
           $numPass=$(echo $Env:STAT | jq '.NumberOfPass')
-          $passedTests=( echo $Env:STAT | jq '.PassedTests'
+          $passedTests=( echo $Env:STAT | jq '.PassedTests')
           echo "*******************${numPass} Passes :) *******************"
           echo $passedTests
           echo "*******************************************************"
+          echo "---------------- ${numFail} Failures :( ----------------------------"
+          echo $failedTests
+          echo "-------------------------------------------------------"
           If ($numFail -gt 0){ exit 2 } 
           If ($numPass -eq 0){ exit 2 }
           If ($numPass -lt 33){ exit 2 }
@@ -415,6 +431,10 @@ jobs:
           ls 
           echo $env:computername
           Get-WmiObject -class Win32_ComputerSystem
+      - uses: actions/setup-go@v2
+        with:
+          go-version: '1.14.6'
+          stable: true
       - name: Install tools
         continue-on-error: true
         shell: powershell
@@ -463,7 +483,7 @@ jobs:
           echo ${GOPOGH_RESULT}
           $numFail=(echo $STAT | jq '.NumberOfFail')
           $failedTests=( echo $STAT | jq '.FailedTests')
-          echo "----------------${numFail} Failures----------------------------"
+          echo "---------------- ${numFail} Failures :( ----------------------------"
           echo $failedTest
           echo "-------------------------------------------------------"
           $numPass=$(echo $STAT | jq '.NumberOfPass')
@@ -477,14 +497,14 @@ jobs:
         run: |
           $numFail=(echo $Env:STAT | jq '.NumberOfFail')
           $failedTests=( echo $Env:STAT | jq '.FailedTests')
-          echo "----------------${numFail} Failures----------------------------"
-          echo $failedTests
-          echo "-------------------------------------------------------"
           $numPass=$(echo $Env:STAT | jq '.NumberOfPass')
-          $passedTests=( echo $Env:STAT | jq '.PassedTests'
+          $passedTests=( echo $Env:STAT | jq '.PassedTests')
           echo "*******************${numPass} Passes :) *******************"
           echo $passedTests
           echo "*******************************************************"
+          echo "---------------- ${numFail} Failures :( ----------------------------"
+          echo $failedTests
+          echo "-------------------------------------------------------"
           If ($numFail -gt 0){ exit 2 } 
           If ($numPass -eq 0){ exit 2 }
           If ($numPass -lt 33){ exit 2 }
@@ -515,7 +535,13 @@ jobs:
           VERSION="v1.17.0"
           curl -L https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/crictl-${VERSION}-linux-amd64.tar.gz --output crictl-${VERSION}-linux-amd64.tar.gz
           sudo tar zxvf crictl-$VERSION-linux-amd64.tar.gz -C /usr/local/bin
+      # go 1.14.6+ is needed because of this bug https://github.com/golang/go/issues/39308
+      - uses: actions/setup-go@v2
+        with:
+          go-version: '1.14.6'
+          stable: true
       - name: Install gopogh
+
         shell: bash
         run: |
           curl -LO https://github.com/medyagh/gopogh/releases/download/v0.2.3/gopogh-linux-amd64
@@ -564,13 +590,13 @@ jobs:
         run: |
           echo ${GOPOGH_RESULT}
           numFail=$(echo $STAT | jq '.NumberOfFail')
-          echo "----------------${numFail} Failures----------------------------"
-          echo $STAT | jq '.FailedTests' || true
-          echo "-------------------------------------------------------"
           numPass=$(echo $STAT | jq '.NumberOfPass')
           echo "*******************${numPass} Passes :) *******************"
           echo $STAT | jq '.PassedTests' || true
           echo "*******************************************************"
+          echo "---------------- ${numFail} Failures :( ----------------------------"
+          echo $STAT | jq '.FailedTests' || true
+          echo "-------------------------------------------------------"
           if [ "$numFail" -gt 0 ];then echo "*** $numFail Failed ***";exit 2;fi
           if [ "$numPass" -eq 0 ];then echo "*** 0 Passed! ***";exit 2;fi
           if [ "$numPass" -lt 26 ];then echo "*** Failed to pass at least 26 ! ***";exit 2;fi
@@ -604,7 +630,13 @@ jobs:
           echo "--------------------------"
           docker ps || true
           echo "--------------------------"
+      # go 1.14.6+ is needed because of this bug https://github.com/golang/go/issues/39308
+      - uses: actions/setup-go@v2
+        with:
+          go-version: '1.14.6'
+          stable: true
       - name: Install gopogh
+
         shell: bash
         run: |
           curl -LO https://github.com/medyagh/gopogh/releases/download/v0.2.3/gopogh-linux-amd64
@@ -653,13 +685,13 @@ jobs:
         run: |
           echo ${GOPOGH_RESULT}
           numFail=$(echo $STAT | jq '.NumberOfFail')
-          echo "----------------${numFail} Failures----------------------------"
-          echo $STAT | jq '.FailedTests' || true
-          echo "-------------------------------------------------------"
           numPass=$(echo $STAT | jq '.NumberOfPass')
           echo "*******************${numPass} Passes :) *******************"
           echo $STAT | jq '.PassedTests' || true
           echo "*******************************************************"
+          echo "---------------- ${numFail} Failures :( ----------------------------"
+          echo $STAT | jq '.FailedTests' || true
+          echo "-------------------------------------------------------"
           if [ "$numFail" -gt 0 ];then echo "*** $numFail Failed ***";exit 2;fi
           if [ "$numPass" -eq 0 ];then echo "*** 0 Passed! ***";exit 2;fi
           if [ "$numPass" -lt 5 ];then echo "*** Failed to pass at least 5 ! ***";exit 2;fi
@@ -678,7 +710,13 @@ jobs:
           curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/darwin/amd64/kubectl
           sudo install kubectl /usr/local/bin/kubectl
           kubectl version --client=true
+      # go 1.14.6+ is needed because of this bug https://github.com/golang/go/issues/39308
+      - uses: actions/setup-go@v2
+        with:
+          go-version: '1.14.6'
+          stable: true
       - name: Install gopogh
+
         shell: bash
         run: |
           curl -LO https://github.com/medyagh/gopogh/releases/download/v0.2.3/gopogh-darwin-amd64
@@ -742,13 +780,13 @@ jobs:
         run: |
           echo ${GOPOGH_RESULT}
           numFail=$(echo $STAT | jq '.NumberOfFail')
-          echo "----------------${numFail} Failures----------------------------"
-          echo $STAT | jq '.FailedTests' || true
-          echo "-------------------------------------------------------"
           numPass=$(echo $STAT | jq '.NumberOfPass')
           echo "*******************${numPass} Passes :) *******************"
           echo $STAT | jq '.PassedTests' || true
           echo "*******************************************************"
+          echo "---------------- ${numFail} Failures :( ----------------------------"
+          echo $STAT | jq '.FailedTests' || true
+          echo "-------------------------------------------------------"
           if [ "$numFail" -gt 0 ];then echo "*** $numFail Failed ***";exit 2;fi
           if [ "$numPass" -eq 0 ];then echo "*** 0 Passed! ***";exit 2;fi
           if [ "$numPass" -lt 5 ];then echo "*** Failed to pass at least 5 ! ***";exit 2;fi
@@ -781,7 +819,13 @@ jobs:
           echo "--------------------------"
           docker ps || true
           echo "--------------------------"
+      # go 1.14.6+ is needed because of this bug https://github.com/golang/go/issues/39308
+      - uses: actions/setup-go@v2
+        with:
+          go-version: '1.14.6'
+          stable: true
       - name: Install gopogh
+
         shell: bash
         run: |
           curl -LO https://github.com/medyagh/gopogh/releases/download/v0.2.3/gopogh-linux-amd64
@@ -832,13 +876,13 @@ jobs:
         run: |
           echo ${GOPOGH_RESULT}
           numFail=$(echo $STAT | jq '.NumberOfFail')
-          echo "----------------${numFail} Failures----------------------------"
-          echo $STAT | jq '.FailedTests' || true
-          echo "-------------------------------------------------------"
           numPass=$(echo $STAT | jq '.NumberOfPass')
           echo "*******************${numPass} Passes :) *******************"
           echo $STAT | jq '.PassedTests' || true
           echo "*******************************************************"
+          echo "---------------- ${numFail} Failures :( ----------------------------"
+          echo $STAT | jq '.FailedTests' || true
+          echo "-------------------------------------------------------"
           if [ "$numFail" -gt 0 ];then echo "*** $numFail Failed ***";exit 2;fi
           if [ "$numPass" -eq 0 ];then echo "*** 0 Passed! ***";exit 2;fi
           if [ "$numPass" -lt 5 ];then echo "*** Failed to pass at least 5 ! ***";exit 2;fi
@@ -857,7 +901,13 @@ jobs:
           curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/darwin/amd64/kubectl
           sudo install kubectl /usr/local/bin/kubectl
           kubectl version --client=true
+      # go 1.14.6+ is needed because of this bug https://github.com/golang/go/issues/39308
+      - uses: actions/setup-go@v2
+        with:
+          go-version: '1.14.6'
+          stable: true
       - name: Install gopogh
+
         shell: bash
         run: |
           curl -LO https://github.com/medyagh/gopogh/releases/download/v0.2.3/gopogh-darwin-amd64
@@ -916,13 +966,13 @@ jobs:
         run: |
           echo ${GOPOGH_RESULT}
           numFail=$(echo $STAT | jq '.NumberOfFail')
-          echo "----------------${numFail} Failures----------------------------"
-          echo $STAT | jq '.FailedTests' || true
-          echo "-------------------------------------------------------"
           numPass=$(echo $STAT | jq '.NumberOfPass')
           echo "*******************${numPass} Passes :) *******************"
           echo $STAT | jq '.PassedTests' || true
           echo "*******************************************************"
+          echo "---------------- ${numFail} Failures :( ----------------------------"
+          echo $STAT | jq '.FailedTests' || true
+          echo "-------------------------------------------------------"
           if [ "$numFail" -gt 0 ];then echo "*** $numFail Failed ***";exit 2;fi
           if [ "$numPass" -eq 0 ];then echo "*** 0 Passed! ***";exit 2;fi
           if [ "$numPass" -lt 7 ];then echo "*** Failed to pass at least 7 ! ***";exit 2;fi
@@ -955,7 +1005,13 @@ jobs:
           echo "--------------------------"
           docker ps || true
           echo "--------------------------"
+      # go 1.14.6+ is needed because of this bug https://github.com/golang/go/issues/39308
+      - uses: actions/setup-go@v2
+        with:
+          go-version: '1.14.6'
+          stable: true
       - name: Install gopogh
+
         shell: bash
         run: |
           curl -LO https://github.com/medyagh/gopogh/releases/download/v0.2.3/gopogh-linux-amd64
@@ -1004,13 +1060,14 @@ jobs:
         run: |
           echo ${GOPOGH_RESULT}
           numFail=$(echo $STAT | jq '.NumberOfFail')
-          echo "----------------${numFail} Failures----------------------------"
-          echo $STAT | jq '.FailedTests' || true
-          echo "-------------------------------------------------------"
           numPass=$(echo $STAT | jq '.NumberOfPass')
           echo "*******************${numPass} Passes :) *******************"
           echo $STAT | jq '.PassedTests' || true
-          echo "*******************************************************"          if [ "$numFail" -gt 0 ];then echo "*** $numFail Failed ***";exit 2;fi
+          echo "*******************************************************"
+          echo "---------------- ${numFail} Failures :( ----------------------------"
+          echo $STAT | jq '.FailedTests' || true
+          echo "-------------------------------------------------------"
+          if [ "$numFail" -gt 0 ];then echo "*** $numFail Failed ***";exit 2;fi
           if [ "$numPass" -eq 0 ];then echo "*** 0 Passed! ***";exit 2;fi
           if [ "$numPass" -lt 9 ];then echo "*** Failed to pass at least 9 ! ***";exit 2;fi
   pause_preload_dockerflags_virtualbox_macos:
@@ -1028,7 +1085,13 @@ jobs:
           curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/darwin/amd64/kubectl
           sudo install kubectl /usr/local/bin/kubectl
           kubectl version --client=true
+      # go 1.14.6+ is needed because of this bug https://github.com/golang/go/issues/39308
+      - uses: actions/setup-go@v2
+        with:
+          go-version: '1.14.6'
+          stable: true
       - name: Install gopogh
+
         shell: bash
         run: |
           curl -LO https://github.com/medyagh/gopogh/releases/download/v0.2.3/gopogh-darwin-amd64
@@ -1087,13 +1150,13 @@ jobs:
         run: |
           echo ${GOPOGH_RESULT}
           numFail=$(echo $STAT | jq '.NumberOfFail')
-          echo "----------------${numFail} Failures----------------------------"
-          echo $STAT | jq '.FailedTests' || true
-          echo "-------------------------------------------------------"
           numPass=$(echo $STAT | jq '.NumberOfPass')
           echo "*******************${numPass} Passes :) *******************"
           echo $STAT | jq '.PassedTests' || true
           echo "*******************************************************"
+          echo "---------------- ${numFail} Failures :( ----------------------------"
+          echo $STAT | jq '.FailedTests' || true
+          echo "-------------------------------------------------------"
           if [ "$numFail" -gt 0 ];then echo "*** $numFail Failed ***";exit 2;fi
           if [ "$numPass" -eq 0 ];then echo "*** 0 Passed! ***";exit 2;fi
           if [ "$numPass" -lt 9 ];then echo "*** Failed to pass at least 9 ! ***";exit 2;fi
