update master workflow

diff --git a/.github/workflows/master.yml b/.github/workflows/master.yml
--- a/.github/workflows/master.yml
+++ b/.github/workflows/master.yml
@@ -866,6 +866,27 @@ jobs:
       GOPOGH_RESULT: ""
       SHELL: "/bin/bash" # To prevent https://github.com/kubernetes/minikube/issues/6643
     steps:
+      - name: Install tools
+        shell: bash
+        run: |
+          sudo apt update
+          sudo apt install -y jq docker git cron
+          sudo usermod -aG docker $USER
+
+      - name: Init
+        shell: bash
+        run: |
+          if [[ -f /var/run/reboot.in.progress ]]; then
+            echo "reboot in progress"
+            exit 1
+          fi
+          sudo touch /var/run/job.in.progress
+          # fix cleanup scripts URL after merge
+          wget https://raw.githubusercontent.com/ilya-zuyev/minikube/ilyaz/gh_actions_cleanup/hack/gh_actions/cleanup.sh
+          wget https://raw.githubusercontent.com/ilya-zuyev/minikube/ilyaz/gh_actions_cleanup/hack/gh_actions/install_cleanup.sh
+          chmod +x cleanup.sh install_cleanup.sh
+          sudo ./install_cleanup.sh
+
       - name: Install kubectl
         shell: bash
         run: |
@@ -878,12 +899,6 @@ jobs:
         run: |
           curl -LO https://github.com/medyagh/gopogh/releases/download/v0.6.0/gopogh-linux-arm64
           sudo install gopogh-linux-arm64 /usr/local/bin/gopogh
-
-      - name: Install tools
-        shell: bash
-        run: |
-          sudo apt update
-          sudo apt install -y jq docker
 
       - name: Docker Info
         shell: bash
