try

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -107,13 +107,15 @@ jobs:
         shell: bash
         run: |
           cd minikube_binaries
-          ST=$(docker run --rm -e NAME="${JOB_NAME} ${GITHUB_REF}" -e REPO="${GITHUB_REPOSITORY}" -e DETAILS="${GITHUB_SHA}" -v ${PWD}/report:/data medyagh/gopogh:v0.1.23 ./text2html.sh || true)
-          ST=$(docker run --rm -e NAME="${JOB_NAME} ${GITHUB_REF}" -e REPO="${GITHUB_REPOSITORY}" -e DETAILS="${GITHUB_SHA}" -v $(pwd)/report:/data medyagh/gopogh:v0.1.23 ./text2html.sh || true)
-          FailNum=(echo $ST | jq '.NumberOfFail')
-          TestsNum=(echo $ST | jq '.NumberOfTests')
-          GRESULT="${JOB_NAME} : completed with ${FailNum} / ${TestsNum} failures in ${TIME_ELAPSED}"
-          echo "::set-env name=GOPOGH_RESULT::${GRESULT}"
-          echo "::set-env name=STATUS::${ST}"
+          export PATH=${PATH}:`go env GOPATH`/bin
+          go tool test2json -t < ./report/testout.txt > ./report/testout.json || true
+          STAT=$(gopogh -in ./report/testout.json -out ./report/testout.html -name "${JOB_NAME} ${GITHUB_REF}" -repo "${GITHUB_REPOSITORY}"  -details "${GITHUB_SHA}")  || true
+          echo status: ${STAT}
+          FailNum=$(echo $STAT | jq '.NumberOfFail')
+          TestsNum=$(echo $STAT | jq '.NumberOfTests')
+          GOPOGH_RESULT="${JOB_NAME} : completed with ${FailNum} / ${TestsNum} failures in ${TIME_ELAPSED}"
+          echo "::set-env name=GOPOGH_RESULT::${GOPOGH_RESULT}"
+          echo "::set-env name=STAT::${STAT}"
       - uses: actions/upload-artifact@v1
         with:
           name: functional_docker_windows
