try

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -107,11 +107,11 @@ jobs:
         shell: bash
         run: |
           cd minikube_binaries
-          $ST=$(docker run --rm -e NAME="${JOB_NAME} ${GITHUB_REF}" -e REPO="${GITHUB_REPOSITORY}" -e DETAILS="${GITHUB_SHA}" -v ${PWD}/report:/data medyagh/gopogh:v0.1.23 ./text2html.sh || true)
-          $ST=$(docker run --rm -e NAME="${JOB_NAME} ${GITHUB_REF}" -e REPO="${GITHUB_REPOSITORY}" -e DETAILS="${GITHUB_SHA}" -v $(pwd)/report:/data medyagh/gopogh:v0.1.23 ./text2html.sh || true)
-          $FailNum=(echo $ST | jq '.NumberOfFail')
-          $TestsNum=(echo $ST | jq '.NumberOfTests')
-          $GRESULT="${JOB_NAME} : completed with ${FailNum} / ${TestsNum} failures in ${TIME_ELAPSED}"
+          ST=$(docker run --rm -e NAME="${JOB_NAME} ${GITHUB_REF}" -e REPO="${GITHUB_REPOSITORY}" -e DETAILS="${GITHUB_SHA}" -v ${PWD}/report:/data medyagh/gopogh:v0.1.23 ./text2html.sh || true)
+          ST=$(docker run --rm -e NAME="${JOB_NAME} ${GITHUB_REF}" -e REPO="${GITHUB_REPOSITORY}" -e DETAILS="${GITHUB_SHA}" -v $(pwd)/report:/data medyagh/gopogh:v0.1.23 ./text2html.sh || true)
+          FailNum=(echo $ST | jq '.NumberOfFail')
+          TestsNum=(echo $ST | jq '.NumberOfTests')
+          GRESULT="${JOB_NAME} : completed with ${FailNum} / ${TestsNum} failures in ${TIME_ELAPSED}"
           echo "::set-env name=GOPOGH_RESULT::${GRESULT}"
           echo "::set-env name=STATUS::${ST}"
       - uses: actions/upload-artifact@v1
